import Head from 'next/head';
import { StoplightProject } from '@stoplight/elements-dev-portal';
import '@stoplight/elements-dev-portal/styles.min.css';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

export default function Guides() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        <a href="/">Home</a>
      </h1>

      <StoplightProject
        projectId="cHJqOjI4MDIz"
        router="memory"
        page="Guides"
      />
      {/* <StoplightProject
        projectId="cHJqOjg3OTYx"
        router="memory"
        page="Guides"
      /> */}
    </div>
  );
}
